name: "Muse"
description: "ðŸŽ§ a self-hosted Discord music bot that doesn't suck "
version: "2.10.0"
slug: "muse"
init: false
image: ghcr.io/museofficial/muse
arch:
  - aarch64
  - amd64
map:
  - type: share
    read_only: False
    path: /data
options:
  discord_token: ""
  spotify_client_id: ""
  spotify_client_secret: ""
  youtube_api_key: ""
schema:
  discord_token: str
  spotify_client_id: str
  spotify_client_secret: str
  youtube_api_key: str
